version: '3.1'

services:
  db:
    container_name: blog_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
  redis:
    container_name: blog_cache
    restart: always
    image: redis:latest
    ports:
      - "6380:6379"
  web:
    container_name: blog
    build: .
    command: python manage.py runserver 0.0.0.0:8000 
    env_file: .venv
    volumes:
      - .:/usr/src/app/
      - ./static:/static
      - ./media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
