version: "3.1"

services:
  db:
    container_name: blog_db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
  redis:
    container_name: blog_cache
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
  nginx:
    container_name: blog_server
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/usr/src/app/static
      - mediafiles:/usr/src/app/media
      - ~/.certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
  web:
    container_name: blog
    build: .
    command: uwsgi -i uwsgi.ini
    restart: always
    env_file: .venv
    volumes: 
      - staticfiles:/usr/src/app/web/static
      - mediafiles:/usr/src/app/web/media
    ports:
      - 8000
    depends_on:
      - db
      - redis

volumes: 
  staticfiles:
  mediafiles:
  mysql:
