# Generated by Django 2.1 on 2018-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('Id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('CheckKey', models.CharField(max_length=8)),
                ('Password', models.CharField(max_length=256)),
                ('UserName', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=50)),
                ('Avatar', models.URLField(max_length=500)),
                ('BgUrls', models.TextField()),
                ('Birthday', models.DateField()),
                ('Email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('Phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('Introduce', models.TextField(max_length=1000)),
                ('Address', models.CharField(max_length=200)),
                ('IP', models.GenericIPAddressField()),
                ('IsEnable', models.BooleanField(default=True)),
                ('Authorized', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
