# Generated by Django 2.1.2 on 2018-11-03 22:30

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('avatar', models.URLField(max_length=500)),
                ('bg_urls', models.TextField()),
                ('birthday', models.DateField(null=True)),
                ('phone', models.CharField(db_index=True, max_length=20, null=True, unique=True)),
                ('introduce', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('is_enable', models.BooleanField(default=True)),
                ('authorized', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Permission')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('content', models.TextField()),
                ('cover', models.URLField(max_length=1000, null=True)),
                ('images', models.TextField(null=True)),
                ('category_ids', models.CharField(max_length=200, null=True)),
                ('tag_ids', models.CharField(max_length=200, null=True)),
                ('hits', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('create_user', models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('spell', models.CharField(db_index=True, max_length=200, unique=True)),
                ('level', models.SmallIntegerField()),
                ('parent_id', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('create_user', models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('spell', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sort', models.IntegerField()),
                ('create_user', models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('size', models.IntegerField()),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('create_user', models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_file',
            },
        ),
    ]
