# Generated by Django 2.1 on 2018-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Birthday',
            field=models.DateField(null=True),
        ),
    ]
