# Generated by Django 2.1 on 2018-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180917_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
