# Generated by Django 2.1 on 2018-10-14 16:10

from django.conf import settings
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180930_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('create_user', models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='create_user',
            field=models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_user',
            field=models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_user',
            field=models.ForeignKey(on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=models.SET(web.models.UserManager.get_deleted_user_id), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
