# Generated by Django 2.1 on 2018-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180917_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Phone',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
